"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import py2app

APP = ['motofit.py']
DATA_FILES = ['icons']
OPTIONS = {'argv_emulation': True,
 'includes':['matplotlib.tri','matplotlib.projections.geo',
 'matplotlib.projections.polar', 'matplotlib.tri.triplot','matplotlib.tri.tripcolor','matplotlib.tri.tricontour',
  'matplotlib.tri.triangulation', 'matplotlib.delaunay.triangulate','sip', 'PySide', 'PySide.QtGui', 'PySide.QtCore',
   'pyplatypus', 'pyplatypus.analysis', 'pyplatypus.dataset', 'pyplatypus.util', 'numdifftools'],
   'excludes':[]}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
