"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import py2app
import periodictable
from distutils.core import *
from distutils      import sysconfig

# Third-party modules - we depend on numpy for everything
import numpy
# Obtain the numpy include directory.  This logic works across numpy versions.
try:
    numpy_include = numpy.get_include()
except AttributeError:
    numpy_include = numpy.get_numpy_include()


APP = ['qt/motofit.py']
DATA_FILES = ['qt/icons']
PACKAGES = ['pyplatypus',
            'periodictable']
            
#  creflect extension module# 
_creflect = Extension("pyplatypus.analysis.__creflect",
                   ["src/reflect.i","src/reflect.c", "src/refcalc.cpp"],
                   include_dirs = [numpy_include],
                   undef_macros=['NDEBUG']
                                 )     
OPTIONS = {'argv_emulation': True,
           'includes':['numdifftools'],
            'packages': PACKAGES,
            'excludes':[]}

setup(
    app=APP,
    data_files=DATA_FILES,
    ext_modules = [_creflect],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
