"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup


APP = ['motofit.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True, 'includes':['matplotlib.tri','matplotlib.projections.geo', 'matplotlib.projections.polar', 'matplotlib.tri.triplot','matplotlib.tri.tripcolor','matplotlib.tri.tricontour', 'matplotlib.tri.triangulation', 'matplotlib.delaunay.triangulate','sip', 'PySide', 'PySide.QtGui', 'PySide.QtCore', 'pyplatypus', 'pyplatypus.analysis', 'pyplatypus.dataset', 'pyplatypus.util']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
