"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import py2app
import periodictable
from distutils.core import *
from distutils import sysconfig
import numpy as np
try:
    from Cython.Distutils import build_ext
except ImportError:
    USE_CYTHON = False
else:
    USE_CYTHON = True

# Obtain the numpy include directory.  This logic works across numpy versions.
try:
    numpy_include = np.get_include()
except AttributeError:
    numpy_include = np.get_numpy_include()

packages = find_packages()

ext_modules = []

if USE_CYTHON:
    # creflect extension module
    _creflect = Extension(
                          name = 'refnx.analysis._creflect',
                          sources=['src/_creflect.pyx', 'src/refcalc.cpp'],
                          include_dirs = [numpy_include],
                          language = 'c',
                          extra_link_args = ['-lpthread']
                          # libraries=
                          # extra_compile_args = "...".split(),
                          )
    ext_modules.append(_creflect)

APP = ['qt/motofit.py']
DATA_FILES = ['qt/icons']
PACKAGES = ['refnx',
            'periodictable']

setup(
    app=APP,
    data_files=DATA_FILES,
    ext_modules=[_creflect],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
